name: Release

on:
  push:
    branches: [ master, beta, alpha ]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          SLACK_TOKEN: https://hooks.slack.com/services/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
          SLACK_NAME: Alert Update Package
          SLACK_CHANNEL: internal-package-release-notification
        run: npx semantic-release